### ISSUE TITLE
Last main menu items not visible when screen height to small

### ISSUE THREAD

**Issue by dontbyte** [nicoandrade/Shophistic-Lite#8] opened 2018-12-31 15:21 UTC
If the screen height is too small and there are a lot of menu items in the main menu then the last ones are not visible anymore. 

Example on your [demo site](http://demo.quemalabs.com/shophistic-lite/):
Let's assume that the "WOMEN" menu item has 15 childs and the screen height is 768px then the last few items will not be visible.

Example with current menu and resized browser window (just to show the basic problem):
![example](https://user-images.githubusercontent.com/25500244/50562831-e8a44780-0d17-11e9-9cf4-394e4683ccd8.jpg)
--> The last item named "Shoes" is not visible anymore.

Any idea how to solve this?

Thanks for all your good work!

**Comment by dontbyte** [comment] 2019-02-02 09:14
@nicoandrade any ideas how to solve this?

Thanks!

**Comment by nicoandrade** [comment] 2019-02-04 12:42
I see that the issue is only when the width of the screen is small. If the windows is wide enough you can scroll to the items:
![Images](https://cl.ly/a5560d1b7b3d/Screen%252520Recording%2525202019-02-04%252520at%25252009.40%252520a.m..gif)

Let me see how to fix the other scenario.

**Comment by nicoandrade** [comment] 2019-02-04 14:08
Fixed on release [v1.0.21](https://github.com/nicoandrade/Shophistic-Lite/releases/tag/v1.0.21)

**Closed as completed by nicoandrade** 2019-02-04 14:08 UTC

**Comment by wprss** [comment] 2019-02-05 07:16
Can't find any changes in the latest commit regarding this issue. 
May I ask how you fixed it?

**Comment by nicoandrade** [comment] 2019-02-05 20:22
The fix for that issue is actually this line:
https://github.com/nicoandrade/Shophistic-Lite/blob/1820f90cdc340a114a768f32c6a3fec20d610fcc/style.css#L61

Now that you mentioned it, looks like it went on an previous commit 🙈
